chart-repos:
  - timberio=https://packages.timber.io/helm/latest
  - timberio-nightly=https://packages.timber.io/helm/nightly
check-version-increment: true
debug: true
helm-extra-args: --timeout 300s
