{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "timber.fullname" . }}
  labels:
    app: {{ template "timber.name" . }}
    chart: {{ template "timber.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["*"]
  resources:
  - cronjobs
  - daemonsets
  - deployments
  - jobs
  - namespaces
  - pods
  - replicasets
  - statefulset
  verbs: ["get"]
{{- end -}}
