apiVersion: v1
kind: Secret
metadata:
  name: {{ template "timber.secretName" . }}
  labels:
    app: {{ template "timber.name" . }}
    chart: {{ template "timber.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  apiKey: {{ required "A valid .Values.timber.apiKey is required!" .Values.timber.apiKey | b64enc | quote }}
