apiVersion: v2
name: vector
type: application
icon: https://vector.dev/press/vector-icon.svg
description: A Helm chart for Vector observability stack
version: "0.16.0-beta.3"
appVersion: "0.15.1"
home: https://vector.dev/
sources:
  - https://github.com/timberio/vector/
maintainers:
  - name: Datadog
    email: team-vector@datadoghq.com
dependencies:
  - name: vector-agent
    version: "*"
    repository: https://helm.vector.dev
  - name: vector-aggregator
    version: "0.16.0-beta.1"
    repository: https://helm.vector.dev
