# Default values for timber-agent
image:
  repository: timberio/agent
  tag: 0.9.2
  pullPolicy: IfNotPresent

# Annotations to add to the DaemonSet's Pods
podAnnotations: {}

# Tolerations to control where the DaemonSet is scheduled (requires Kubernetes >= 1.6)
daemonsetTolerations: []

# Allow the DaemonSet to perform a rolling update on helm update
# https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/
updateStrategy: OnDelete

timber:
  # You'll need to set this to your Timber API key before the agent will run
  # https://timber.io/docs/app/applications/obtaining-api-key/
  #
  # apiKey: TIMBER_API_KEY

  # TOML document for setting the Timber Agent configuration
  # The full list of options can be found here:
  # https://timber.io/docs/platforms/other/agent/configuration-file/
  # https://timber.io/docs/platforms/kubernetes/configuration
  config: |
    [kubernetes.exclude]
    namespaces = "kube-system"
    pods = "timber-agent"

  # Image containing kubectl binary used to run `kubectl proxy`
  proxyImage: timberio/kubectl:1.10.0

  # Address Kubernetes API proxy listens on
  proxyHost: localhost

  # Port Kubernetes API proxy listens on
  proxyPort: 8001

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 200Mi
  # requests:
  #  cpu: 100m
  #  memory: 100Mi

rbac:
  # Specifies whether RBAC resources should be created
  create: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: false
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
